//
//  PeriodicTableBackground.swift
//  Periodic Table
//
//  Created by Swift Mage on 11/12/2017.
//  Copyright © 2017 Swift Mage. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class PeriodicTableBackground : NSObject {

    //// Cache

    private struct Cache {
        static let hydrogenColor: UIColor = UIColor(red: 0.595, green: 1.000, blue: 0.611, alpha: 1.000)
        static let alkaliMetalsColor: UIColor = UIColor(red: 1.000, green: 0.862, blue: 0.483, alpha: 1.000)
        static let alkalineEarthMetalsColor: UIColor = UIColor(red: 0.996, green: 0.998, blue: 0.409, alpha: 1.000)
        static let transitionMetalsColor: UIColor = UIColor(red: 0.892, green: 0.780, blue: 0.782, alpha: 1.000)
        static let postTransitionMetalColor: UIColor = UIColor(red: 0.569, green: 0.827, blue: 0.762, alpha: 1.000)
        static let metalloidsColor: UIColor = UIColor(red: 0.464, green: 0.869, blue: 0.532, alpha: 1.000)
        static let otherNonMetalsColor: UIColor = UIColor(red: 0.125, green: 1.000, blue: 0.127, alpha: 1.000)
        static let nobleGasesColor: UIColor = UIColor(red: 0.464, green: 0.800, blue: 0.999, alpha: 1.000)
        static let unknownColor: UIColor = UIColor(red: 0.890, green: 0.890, blue: 0.890, alpha: 1.000)
        static let lanthanoidsColor: UIColor = UIColor(red: 1.000, green: 0.777, blue: 0.661, alpha: 1.000)
        static let actinoidsColor: UIColor = UIColor(red: 0.932, green: 0.735, blue: 0.866, alpha: 1.000)
        static let gradientColor: UIColor = UIColor(red: 0.512, green: 0.860, blue: 0.526, alpha: 1.000)
    }

    //// Colors

    @objc dynamic public class var hydrogenColor: UIColor { return Cache.hydrogenColor }
    @objc dynamic public class var alkaliMetalsColor: UIColor { return Cache.alkaliMetalsColor }
    @objc dynamic public class var alkalineEarthMetalsColor: UIColor { return Cache.alkalineEarthMetalsColor }
    @objc dynamic public class var transitionMetalsColor: UIColor { return Cache.transitionMetalsColor }
    @objc dynamic public class var postTransitionMetalColor: UIColor { return Cache.postTransitionMetalColor }
    @objc dynamic public class var metalloidsColor: UIColor { return Cache.metalloidsColor }
    @objc dynamic public class var otherNonMetalsColor: UIColor { return Cache.otherNonMetalsColor }
    @objc dynamic public class var nobleGasesColor: UIColor { return Cache.nobleGasesColor }
    @objc dynamic public class var unknownColor: UIColor { return Cache.unknownColor }
    @objc dynamic public class var lanthanoidsColor: UIColor { return Cache.lanthanoidsColor }
    @objc dynamic public class var actinoidsColor: UIColor { return Cache.actinoidsColor }
    @objc dynamic public class var gradientColor: UIColor { return Cache.gradientColor }

    //// Drawing Methods

    @objc dynamic public class func drawPeriodicTableLandscape(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 667, height: 375), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 667, height: 375), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 667, y: resizedFrame.height / 375)


        //// Element 1 Drawing
        let element1Path = UIBezierPath(rect: CGRect(x: 17, y: 40, width: 35, height: 35))
        PeriodicTableBackground.hydrogenColor.setFill()
        element1Path.fill()


        //// Element 3 Drawing
        let element3Path = UIBezierPath(rect: CGRect(x: 17, y: 75, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element3Path.fill()


        //// Element 11 Drawing
        let element11Path = UIBezierPath(rect: CGRect(x: 17, y: 110, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element11Path.fill()


        //// Element 19 Drawing
        let element19Path = UIBezierPath(rect: CGRect(x: 17, y: 145, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element19Path.fill()


        //// Element 37 Drawing
        let element37Path = UIBezierPath(rect: CGRect(x: 17, y: 180, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element37Path.fill()


        //// Element 55 Drawing
        let element55Path = UIBezierPath(rect: CGRect(x: 17, y: 215, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element55Path.fill()


        //// Element 87 Drawing
        let element87Path = UIBezierPath(rect: CGRect(x: 17, y: 250, width: 35, height: 35))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        element87Path.fill()


        //// Element 4 Drawing
        let element4Path = UIBezierPath(rect: CGRect(x: 52, y: 75, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element4Path.fill()


        //// Element 12 Drawing
        let element12Path = UIBezierPath(rect: CGRect(x: 52, y: 110, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element12Path.fill()


        //// Element 20 Drawing
        let element20Path = UIBezierPath(rect: CGRect(x: 52, y: 145, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element20Path.fill()


        //// Element 38 Drawing
        let element38Path = UIBezierPath(rect: CGRect(x: 52, y: 180, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element38Path.fill()


        //// Element 56 Drawing
        let element56Path = UIBezierPath(rect: CGRect(x: 52, y: 215, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element56Path.fill()


        //// Element 88 Drawing
        let element88Path = UIBezierPath(rect: CGRect(x: 52, y: 250, width: 35, height: 35))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        element88Path.fill()


        //// Element 21 Drawing
        let element21Path = UIBezierPath(rect: CGRect(x: 87, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element21Path.fill()


        //// Element 39 Drawing
        let element39Path = UIBezierPath(rect: CGRect(x: 87, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element39Path.fill()


        //// Lanthanoids Cell Drawing
        let lanthanoidsCellPath = UIBezierPath(rect: CGRect(x: 87, y: 215, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        lanthanoidsCellPath.fill()


        //// Actinoids Cell Drawing
        let actinoidsCellPath = UIBezierPath(rect: CGRect(x: 87, y: 250, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        actinoidsCellPath.fill()


        //// Element 22 Drawing
        let element22Path = UIBezierPath(rect: CGRect(x: 122, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element22Path.fill()


        //// Element 40 Drawing
        let element40Path = UIBezierPath(rect: CGRect(x: 122, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element40Path.fill()


        //// Element 72 Drawing
        let element72Path = UIBezierPath(rect: CGRect(x: 122, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element72Path.fill()


        //// Element 104 Drawing
        let element104Path = UIBezierPath(rect: CGRect(x: 122, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element104Path.fill()


        //// Element 23 Drawing
        let element23Path = UIBezierPath(rect: CGRect(x: 157, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element23Path.fill()


        //// Element 41 Drawing
        let element41Path = UIBezierPath(rect: CGRect(x: 157, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element41Path.fill()


        //// Element 73 Drawing
        let element73Path = UIBezierPath(rect: CGRect(x: 157, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element73Path.fill()


        //// Element 105 Drawing
        let element105Path = UIBezierPath(rect: CGRect(x: 157, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element105Path.fill()


        //// Element 24 Drawing
        let element24Path = UIBezierPath(rect: CGRect(x: 192, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element24Path.fill()


        //// Element 42 Drawing
        let element42Path = UIBezierPath(rect: CGRect(x: 192, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element42Path.fill()


        //// Element 74 Drawing
        let element74Path = UIBezierPath(rect: CGRect(x: 192, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element74Path.fill()


        //// Element 106 Drawing
        let element106Path = UIBezierPath(rect: CGRect(x: 192, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element106Path.fill()


        //// Element 25 Drawing
        let element25Path = UIBezierPath(rect: CGRect(x: 227, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element25Path.fill()


        //// Element 43 Drawing
        let element43Path = UIBezierPath(rect: CGRect(x: 227, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element43Path.fill()


        //// Element 75 Drawing
        let element75Path = UIBezierPath(rect: CGRect(x: 227, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element75Path.fill()


        //// Element 107 Drawing
        let element107Path = UIBezierPath(rect: CGRect(x: 227, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element107Path.fill()


        //// Element 26 Drawing
        let element26Path = UIBezierPath(rect: CGRect(x: 262, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element26Path.fill()


        //// Element 44 Drawing
        let element44Path = UIBezierPath(rect: CGRect(x: 262, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element44Path.fill()


        //// Element 76 Drawing
        let element76Path = UIBezierPath(rect: CGRect(x: 262, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element76Path.fill()


        //// Element 108 Drawing
        let element108Path = UIBezierPath(rect: CGRect(x: 262, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element108Path.fill()


        //// Element 27 Drawing
        let element27Path = UIBezierPath(rect: CGRect(x: 297, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element27Path.fill()


        //// Element 45 Drawing
        let element45Path = UIBezierPath(rect: CGRect(x: 297, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element45Path.fill()


        //// Element 77 Drawing
        let element77Path = UIBezierPath(rect: CGRect(x: 297, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element77Path.fill()


        //// Element 109 Drawing
        let element109Path = UIBezierPath(rect: CGRect(x: 297, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element109Path.fill()


        //// Element 28 Drawing
        let element28Path = UIBezierPath(rect: CGRect(x: 332, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element28Path.fill()


        //// Element 46 Drawing
        let element46Path = UIBezierPath(rect: CGRect(x: 332, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element46Path.fill()


        //// Element 78 Drawing
        let element78Path = UIBezierPath(rect: CGRect(x: 332, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element78Path.fill()


        //// Element 110 Drawing
        let element110Path = UIBezierPath(rect: CGRect(x: 332, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element110Path.fill()


        //// Element 29 Drawing
        let element29Path = UIBezierPath(rect: CGRect(x: 367, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element29Path.fill()


        //// Element 47 Drawing
        let element47Path = UIBezierPath(rect: CGRect(x: 367, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element47Path.fill()


        //// Element 79 Drawing
        let element79Path = UIBezierPath(rect: CGRect(x: 367, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element79Path.fill()


        //// Element 111 Drawing
        let element111Path = UIBezierPath(rect: CGRect(x: 367, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element111Path.fill()


        //// Element 30 Drawing
        let element30Path = UIBezierPath(rect: CGRect(x: 402, y: 145, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element30Path.fill()


        //// Element 48 Drawing
        let element48Path = UIBezierPath(rect: CGRect(x: 402, y: 180, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element48Path.fill()


        //// Element 80 Drawing
        let element80Path = UIBezierPath(rect: CGRect(x: 402, y: 215, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element80Path.fill()


        //// Element 112 Drawing
        let element112Path = UIBezierPath(rect: CGRect(x: 402, y: 250, width: 35, height: 35))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        element112Path.fill()


        //// Element 31 Drawing
        let element31Path = UIBezierPath(rect: CGRect(x: 437, y: 145, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element31Path.fill()


        //// Element 13 Drawing
        let element13Path = UIBezierPath(rect: CGRect(x: 437, y: 110, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element13Path.fill()


        //// Element 49 Drawing
        let element49Path = UIBezierPath(rect: CGRect(x: 437, y: 180, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element49Path.fill()


        //// Element 81 Drawing
        let element81Path = UIBezierPath(rect: CGRect(x: 437, y: 215, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element81Path.fill()


        //// Element 5 Drawing
        let element5Path = UIBezierPath(rect: CGRect(x: 437, y: 75, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element5Path.fill()


        //// Element 113 Drawing
        let element113Path = UIBezierPath(rect: CGRect(x: 437, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element113Path.fill()


        //// Element 32 Drawing
        let element32Path = UIBezierPath(rect: CGRect(x: 472, y: 145, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element32Path.fill()


        //// Element 14 Drawing
        let element14Path = UIBezierPath(rect: CGRect(x: 472, y: 110, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element14Path.fill()


        //// Element 50 Drawing
        let element50Path = UIBezierPath(rect: CGRect(x: 472, y: 180, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element50Path.fill()


        //// Element 82 Drawing
        let element82Path = UIBezierPath(rect: CGRect(x: 472, y: 215, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element82Path.fill()


        //// Element 6 Drawing
        let element6Path = UIBezierPath(rect: CGRect(x: 472, y: 75, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element6Path.fill()


        //// Element 114 Drawing
        let element114Path = UIBezierPath(rect: CGRect(x: 472, y: 250, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element114Path.fill()


        //// Element 33 Drawing
        let element33Path = UIBezierPath(rect: CGRect(x: 507, y: 145, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element33Path.fill()


        //// Element 15 Drawing
        let element15Path = UIBezierPath(rect: CGRect(x: 507, y: 110, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element15Path.fill()


        //// Element 51 Drawing
        let element51Path = UIBezierPath(rect: CGRect(x: 507, y: 180, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element51Path.fill()


        //// Element 83 Drawing
        let element83Path = UIBezierPath(rect: CGRect(x: 507, y: 215, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element83Path.fill()


        //// Element 7 Drawing
        let element7Path = UIBezierPath(rect: CGRect(x: 507, y: 75, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element7Path.fill()


        //// Element 115 Drawing
        let element115Path = UIBezierPath(rect: CGRect(x: 507, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element115Path.fill()


        //// Element 34 Drawing
        let element34Path = UIBezierPath(rect: CGRect(x: 542, y: 145, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element34Path.fill()


        //// Element 16 Drawing
        let element16Path = UIBezierPath(rect: CGRect(x: 542, y: 110, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element16Path.fill()


        //// Element 52 Drawing
        let element52Path = UIBezierPath(rect: CGRect(x: 542, y: 180, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element52Path.fill()


        //// Element 84 Drawing
        let element84Path = UIBezierPath(rect: CGRect(x: 542, y: 215, width: 35, height: 35))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        element84Path.fill()


        //// Element 8 Drawing
        let element8Path = UIBezierPath(rect: CGRect(x: 542, y: 75, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element8Path.fill()


        //// Element 116 Drawing
        let element116Path = UIBezierPath(rect: CGRect(x: 542, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element116Path.fill()


        //// Element 35 Drawing
        let element35Path = UIBezierPath(rect: CGRect(x: 577, y: 145, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element35Path.fill()


        //// Element 17 Drawing
        let element17Path = UIBezierPath(rect: CGRect(x: 577, y: 110, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element17Path.fill()


        //// Element 53 Drawing
        let element53Path = UIBezierPath(rect: CGRect(x: 577, y: 180, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element53Path.fill()


        //// Element 85 Drawing
        let element85Path = UIBezierPath(rect: CGRect(x: 577, y: 215, width: 35, height: 35))
        PeriodicTableBackground.metalloidsColor.setFill()
        element85Path.fill()


        //// Element 9 Drawing
        let element9Path = UIBezierPath(rect: CGRect(x: 577, y: 75, width: 35, height: 35))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        element9Path.fill()


        //// Element 117 Drawing
        let element117Path = UIBezierPath(rect: CGRect(x: 577, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element117Path.fill()


        //// Element 36 Drawing
        let element36Path = UIBezierPath(rect: CGRect(x: 612, y: 145, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element36Path.fill()


        //// Element 18 Drawing
        let element18Path = UIBezierPath(rect: CGRect(x: 612, y: 110, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element18Path.fill()


        //// Element 54 Drawing
        let element54Path = UIBezierPath(rect: CGRect(x: 612, y: 180, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element54Path.fill()


        //// Element 86 Drawing
        let element86Path = UIBezierPath(rect: CGRect(x: 612, y: 215, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element86Path.fill()


        //// Element 10 Drawing
        let element10Path = UIBezierPath(rect: CGRect(x: 612, y: 75, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element10Path.fill()


        //// Element 118 Drawing
        let element118Path = UIBezierPath(rect: CGRect(x: 612, y: 250, width: 35, height: 35))
        PeriodicTableBackground.unknownColor.setFill()
        element118Path.fill()


        //// Element 2 Drawing
        let element2Path = UIBezierPath(rect: CGRect(x: 612, y: 40, width: 35, height: 35))
        PeriodicTableBackground.nobleGasesColor.setFill()
        element2Path.fill()


        //// Element 57 Drawing
        let element57Path = UIBezierPath(rect: CGRect(x: 122, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element57Path.fill()


        //// Element 58 Drawing
        let element58Path = UIBezierPath(rect: CGRect(x: 157, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element58Path.fill()


        //// Element 59 Drawing
        let element59Path = UIBezierPath(rect: CGRect(x: 192, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element59Path.fill()


        //// Element 60 Drawing
        let element60Path = UIBezierPath(rect: CGRect(x: 227, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element60Path.fill()


        //// Element 61 Drawing
        let element61Path = UIBezierPath(rect: CGRect(x: 262, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element61Path.fill()


        //// Element 62 Drawing
        let element62Path = UIBezierPath(rect: CGRect(x: 297, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element62Path.fill()


        //// Element 63 Drawing
        let element63Path = UIBezierPath(rect: CGRect(x: 332, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element63Path.fill()


        //// Element 64 Drawing
        let element64Path = UIBezierPath(rect: CGRect(x: 367, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element64Path.fill()


        //// Element 65 Drawing
        let element65Path = UIBezierPath(rect: CGRect(x: 402, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element65Path.fill()


        //// Element 66 Drawing
        let element66Path = UIBezierPath(rect: CGRect(x: 437, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element66Path.fill()


        //// Element 67 Drawing
        let element67Path = UIBezierPath(rect: CGRect(x: 472, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element67Path.fill()


        //// Element 68 Drawing
        let element68Path = UIBezierPath(rect: CGRect(x: 507, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element68Path.fill()


        //// Element 69 Drawing
        let element69Path = UIBezierPath(rect: CGRect(x: 542, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element69Path.fill()


        //// Element 70 Drawing
        let element70Path = UIBezierPath(rect: CGRect(x: 577, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element70Path.fill()


        //// Element 71 Drawing
        let element71Path = UIBezierPath(rect: CGRect(x: 612, y: 296, width: 35, height: 35))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        element71Path.fill()


        //// Element Drawing
        let elementPath = UIBezierPath(rect: CGRect(x: 612, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        elementPath.fill()


        //// Element 89 Drawing
        let element89Path = UIBezierPath(rect: CGRect(x: 122, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element89Path.fill()


        //// Element 90 Drawing
        let element90Path = UIBezierPath(rect: CGRect(x: 157, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element90Path.fill()


        //// Element 91 Drawing
        let element91Path = UIBezierPath(rect: CGRect(x: 192, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element91Path.fill()


        //// Element 92 Drawing
        let element92Path = UIBezierPath(rect: CGRect(x: 227, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element92Path.fill()


        //// Element 93 Drawing
        let element93Path = UIBezierPath(rect: CGRect(x: 262, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element93Path.fill()


        //// Element 94 Drawing
        let element94Path = UIBezierPath(rect: CGRect(x: 297, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element94Path.fill()


        //// Element 95 Drawing
        let element95Path = UIBezierPath(rect: CGRect(x: 332, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element95Path.fill()


        //// Element 96 Drawing
        let element96Path = UIBezierPath(rect: CGRect(x: 367, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element96Path.fill()


        //// Element 97 Drawing
        let element97Path = UIBezierPath(rect: CGRect(x: 402, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element97Path.fill()


        //// Element 98 Drawing
        let element98Path = UIBezierPath(rect: CGRect(x: 437, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element98Path.fill()


        //// Element 99 Drawing
        let element99Path = UIBezierPath(rect: CGRect(x: 472, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element99Path.fill()


        //// Element 100 Drawing
        let element100Path = UIBezierPath(rect: CGRect(x: 507, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element100Path.fill()


        //// Element 101 Drawing
        let element101Path = UIBezierPath(rect: CGRect(x: 542, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element101Path.fill()


        //// Element 102 Drawing
        let element102Path = UIBezierPath(rect: CGRect(x: 577, y: 331, width: 35, height: 35))
        PeriodicTableBackground.actinoidsColor.setFill()
        element102Path.fill()


        //// Period1Label Drawing
        let period1LabelRect = CGRect(x: 0, y: 47, width: 17, height: 21)
        let period1LabelTextContent = "1"
        let period1LabelStyle = NSMutableParagraphStyle()
        period1LabelStyle.alignment = .center
        let period1LabelFontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1LabelStyle,
        ] as [NSAttributedStringKey: Any]

        let period1LabelTextHeight: CGFloat = period1LabelTextContent.boundingRect(with: CGSize(width: period1LabelRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1LabelFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1LabelRect)
        period1LabelTextContent.draw(in: CGRect(x: period1LabelRect.minX, y: period1LabelRect.minY + (period1LabelRect.height - period1LabelTextHeight) / 2, width: period1LabelRect.width, height: period1LabelTextHeight), withAttributes: period1LabelFontAttributes)
        context.restoreGState()


        //// Period1Label 2 Drawing
        let period1Label2Rect = CGRect(x: 0, y: 82, width: 17, height: 21)
        let period1Label2TextContent = "2"
        let period1Label2Style = NSMutableParagraphStyle()
        period1Label2Style.alignment = .center
        let period1Label2FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label2Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label2TextHeight: CGFloat = period1Label2TextContent.boundingRect(with: CGSize(width: period1Label2Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label2FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label2Rect)
        period1Label2TextContent.draw(in: CGRect(x: period1Label2Rect.minX, y: period1Label2Rect.minY + (period1Label2Rect.height - period1Label2TextHeight) / 2, width: period1Label2Rect.width, height: period1Label2TextHeight), withAttributes: period1Label2FontAttributes)
        context.restoreGState()


        //// Period1Label 3 Drawing
        let period1Label3Rect = CGRect(x: 0, y: 117, width: 17, height: 21)
        let period1Label3TextContent = "3"
        let period1Label3Style = NSMutableParagraphStyle()
        period1Label3Style.alignment = .center
        let period1Label3FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label3Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label3TextHeight: CGFloat = period1Label3TextContent.boundingRect(with: CGSize(width: period1Label3Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label3FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label3Rect)
        period1Label3TextContent.draw(in: CGRect(x: period1Label3Rect.minX, y: period1Label3Rect.minY + (period1Label3Rect.height - period1Label3TextHeight) / 2, width: period1Label3Rect.width, height: period1Label3TextHeight), withAttributes: period1Label3FontAttributes)
        context.restoreGState()


        //// Period1Label 4 Drawing
        let period1Label4Rect = CGRect(x: 0, y: 152, width: 17, height: 21)
        let period1Label4TextContent = "4"
        let period1Label4Style = NSMutableParagraphStyle()
        period1Label4Style.alignment = .center
        let period1Label4FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label4Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label4TextHeight: CGFloat = period1Label4TextContent.boundingRect(with: CGSize(width: period1Label4Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label4FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label4Rect)
        period1Label4TextContent.draw(in: CGRect(x: period1Label4Rect.minX, y: period1Label4Rect.minY + (period1Label4Rect.height - period1Label4TextHeight) / 2, width: period1Label4Rect.width, height: period1Label4TextHeight), withAttributes: period1Label4FontAttributes)
        context.restoreGState()


        //// Period1Label 5 Drawing
        let period1Label5Rect = CGRect(x: 0, y: 187, width: 17, height: 21)
        let period1Label5TextContent = "5"
        let period1Label5Style = NSMutableParagraphStyle()
        period1Label5Style.alignment = .center
        let period1Label5FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label5Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label5TextHeight: CGFloat = period1Label5TextContent.boundingRect(with: CGSize(width: period1Label5Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label5FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label5Rect)
        period1Label5TextContent.draw(in: CGRect(x: period1Label5Rect.minX, y: period1Label5Rect.minY + (period1Label5Rect.height - period1Label5TextHeight) / 2, width: period1Label5Rect.width, height: period1Label5TextHeight), withAttributes: period1Label5FontAttributes)
        context.restoreGState()


        //// Period1Label 6 Drawing
        let period1Label6Rect = CGRect(x: 0, y: 222, width: 17, height: 21)
        let period1Label6TextContent = "6"
        let period1Label6Style = NSMutableParagraphStyle()
        period1Label6Style.alignment = .center
        let period1Label6FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label6Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label6TextHeight: CGFloat = period1Label6TextContent.boundingRect(with: CGSize(width: period1Label6Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label6FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label6Rect)
        period1Label6TextContent.draw(in: CGRect(x: period1Label6Rect.minX, y: period1Label6Rect.minY + (period1Label6Rect.height - period1Label6TextHeight) / 2, width: period1Label6Rect.width, height: period1Label6TextHeight), withAttributes: period1Label6FontAttributes)
        context.restoreGState()


        //// Period1Label 7 Drawing
        let period1Label7Rect = CGRect(x: 0, y: 257, width: 17, height: 21)
        let period1Label7TextContent = "7"
        let period1Label7Style = NSMutableParagraphStyle()
        period1Label7Style.alignment = .center
        let period1Label7FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: period1Label7Style,
        ] as [NSAttributedStringKey: Any]

        let period1Label7TextHeight: CGFloat = period1Label7TextContent.boundingRect(with: CGSize(width: period1Label7Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: period1Label7FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: period1Label7Rect)
        period1Label7TextContent.draw(in: CGRect(x: period1Label7Rect.minX, y: period1Label7Rect.minY + (period1Label7Rect.height - period1Label7TextHeight) / 2, width: period1Label7Rect.width, height: period1Label7TextHeight), withAttributes: period1Label7FontAttributes)
        context.restoreGState()


        //// Group 1 Drawing
        let group1Rect = CGRect(x: 17, y: 20, width: 35, height: 20)
        let group1TextContent = "IA"
        let group1Style = NSMutableParagraphStyle()
        group1Style.alignment = .center
        let group1FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group1Style,
        ] as [NSAttributedStringKey: Any]

        let group1TextHeight: CGFloat = group1TextContent.boundingRect(with: CGSize(width: group1Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group1FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group1Rect)
        group1TextContent.draw(in: CGRect(x: group1Rect.minX, y: group1Rect.minY + (group1Rect.height - group1TextHeight) / 2, width: group1Rect.width, height: group1TextHeight), withAttributes: group1FontAttributes)
        context.restoreGState()


        //// Group 2 Drawing
        let group2Rect = CGRect(x: 53, y: 20, width: 35, height: 20)
        let group2TextContent = "IIA"
        let group2Style = NSMutableParagraphStyle()
        group2Style.alignment = .center
        let group2FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group2Style,
        ] as [NSAttributedStringKey: Any]

        let group2TextHeight: CGFloat = group2TextContent.boundingRect(with: CGSize(width: group2Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group2FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group2Rect)
        group2TextContent.draw(in: CGRect(x: group2Rect.minX, y: group2Rect.minY + (group2Rect.height - group2TextHeight) / 2, width: group2Rect.width, height: group2TextHeight), withAttributes: group2FontAttributes)
        context.restoreGState()


        //// Group 3 Drawing
        let group3Rect = CGRect(x: 88, y: 20, width: 35, height: 20)
        let group3TextContent = "IIIB"
        let group3Style = NSMutableParagraphStyle()
        group3Style.alignment = .center
        let group3FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group3Style,
        ] as [NSAttributedStringKey: Any]

        let group3TextHeight: CGFloat = group3TextContent.boundingRect(with: CGSize(width: group3Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group3FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group3Rect)
        group3TextContent.draw(in: CGRect(x: group3Rect.minX, y: group3Rect.minY + (group3Rect.height - group3TextHeight) / 2, width: group3Rect.width, height: group3TextHeight), withAttributes: group3FontAttributes)
        context.restoreGState()


        //// Group 4 Drawing
        let group4Rect = CGRect(x: 122, y: 20, width: 35, height: 20)
        let group4TextContent = "IVB"
        let group4Style = NSMutableParagraphStyle()
        group4Style.alignment = .center
        let group4FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group4Style,
        ] as [NSAttributedStringKey: Any]

        let group4TextHeight: CGFloat = group4TextContent.boundingRect(with: CGSize(width: group4Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group4FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group4Rect)
        group4TextContent.draw(in: CGRect(x: group4Rect.minX, y: group4Rect.minY + (group4Rect.height - group4TextHeight) / 2, width: group4Rect.width, height: group4TextHeight), withAttributes: group4FontAttributes)
        context.restoreGState()


        //// Group 5 Drawing
        let group5Rect = CGRect(x: 157, y: 20, width: 35, height: 20)
        let group5TextContent = "VB"
        let group5Style = NSMutableParagraphStyle()
        group5Style.alignment = .center
        let group5FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group5Style,
        ] as [NSAttributedStringKey: Any]

        let group5TextHeight: CGFloat = group5TextContent.boundingRect(with: CGSize(width: group5Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group5FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group5Rect)
        group5TextContent.draw(in: CGRect(x: group5Rect.minX, y: group5Rect.minY + (group5Rect.height - group5TextHeight) / 2, width: group5Rect.width, height: group5TextHeight), withAttributes: group5FontAttributes)
        context.restoreGState()


        //// Group 6 Drawing
        let group6Rect = CGRect(x: 192, y: 20, width: 35, height: 20)
        let group6TextContent = "VIB"
        let group6Style = NSMutableParagraphStyle()
        group6Style.alignment = .center
        let group6FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group6Style,
        ] as [NSAttributedStringKey: Any]

        let group6TextHeight: CGFloat = group6TextContent.boundingRect(with: CGSize(width: group6Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group6FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group6Rect)
        group6TextContent.draw(in: CGRect(x: group6Rect.minX, y: group6Rect.minY + (group6Rect.height - group6TextHeight) / 2, width: group6Rect.width, height: group6TextHeight), withAttributes: group6FontAttributes)
        context.restoreGState()


        //// Group 7 Drawing
        let group7Rect = CGRect(x: 227, y: 20, width: 35, height: 20)
        let group7TextContent = "VIIB"
        let group7Style = NSMutableParagraphStyle()
        group7Style.alignment = .center
        let group7FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group7Style,
        ] as [NSAttributedStringKey: Any]

        let group7TextHeight: CGFloat = group7TextContent.boundingRect(with: CGSize(width: group7Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group7FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group7Rect)
        group7TextContent.draw(in: CGRect(x: group7Rect.minX, y: group7Rect.minY + (group7Rect.height - group7TextHeight) / 2, width: group7Rect.width, height: group7TextHeight), withAttributes: group7FontAttributes)
        context.restoreGState()


        //// Group 8 Drawing
        let group8Rect = CGRect(x: 262, y: 20, width: 105, height: 20)
        let group8TextContent = "VIIIB"
        let group8Style = NSMutableParagraphStyle()
        group8Style.alignment = .center
        let group8FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group8Style,
        ] as [NSAttributedStringKey: Any]

        let group8TextHeight: CGFloat = group8TextContent.boundingRect(with: CGSize(width: group8Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group8FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group8Rect)
        group8TextContent.draw(in: CGRect(x: group8Rect.minX, y: group8Rect.minY + (group8Rect.height - group8TextHeight) / 2, width: group8Rect.width, height: group8TextHeight), withAttributes: group8FontAttributes)
        context.restoreGState()


        //// Group 11 Drawing
        let group11Rect = CGRect(x: 367, y: 20, width: 35, height: 20)
        let group11TextContent = "IB"
        let group11Style = NSMutableParagraphStyle()
        group11Style.alignment = .center
        let group11FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group11Style,
        ] as [NSAttributedStringKey: Any]

        let group11TextHeight: CGFloat = group11TextContent.boundingRect(with: CGSize(width: group11Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group11FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group11Rect)
        group11TextContent.draw(in: CGRect(x: group11Rect.minX, y: group11Rect.minY + (group11Rect.height - group11TextHeight) / 2, width: group11Rect.width, height: group11TextHeight), withAttributes: group11FontAttributes)
        context.restoreGState()


        //// Group 12 Drawing
        let group12Rect = CGRect(x: 402, y: 20, width: 35, height: 20)
        let group12TextContent = "IIB"
        let group12Style = NSMutableParagraphStyle()
        group12Style.alignment = .center
        let group12FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group12Style,
        ] as [NSAttributedStringKey: Any]

        let group12TextHeight: CGFloat = group12TextContent.boundingRect(with: CGSize(width: group12Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group12FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group12Rect)
        group12TextContent.draw(in: CGRect(x: group12Rect.minX, y: group12Rect.minY + (group12Rect.height - group12TextHeight) / 2, width: group12Rect.width, height: group12TextHeight), withAttributes: group12FontAttributes)
        context.restoreGState()


        //// Group 13 Drawing
        let group13Rect = CGRect(x: 437, y: 20, width: 35, height: 20)
        let group13TextContent = "IIIA"
        let group13Style = NSMutableParagraphStyle()
        group13Style.alignment = .center
        let group13FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group13Style,
        ] as [NSAttributedStringKey: Any]

        let group13TextHeight: CGFloat = group13TextContent.boundingRect(with: CGSize(width: group13Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group13FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group13Rect)
        group13TextContent.draw(in: CGRect(x: group13Rect.minX, y: group13Rect.minY + (group13Rect.height - group13TextHeight) / 2, width: group13Rect.width, height: group13TextHeight), withAttributes: group13FontAttributes)
        context.restoreGState()


        //// Group 14 Drawing
        let group14Rect = CGRect(x: 472, y: 20, width: 35, height: 20)
        let group14TextContent = "IVA"
        let group14Style = NSMutableParagraphStyle()
        group14Style.alignment = .center
        let group14FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group14Style,
        ] as [NSAttributedStringKey: Any]

        let group14TextHeight: CGFloat = group14TextContent.boundingRect(with: CGSize(width: group14Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group14FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group14Rect)
        group14TextContent.draw(in: CGRect(x: group14Rect.minX, y: group14Rect.minY + (group14Rect.height - group14TextHeight) / 2, width: group14Rect.width, height: group14TextHeight), withAttributes: group14FontAttributes)
        context.restoreGState()


        //// Group 15 Drawing
        let group15Rect = CGRect(x: 507, y: 20, width: 35, height: 20)
        let group15TextContent = "VA"
        let group15Style = NSMutableParagraphStyle()
        group15Style.alignment = .center
        let group15FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group15Style,
        ] as [NSAttributedStringKey: Any]

        let group15TextHeight: CGFloat = group15TextContent.boundingRect(with: CGSize(width: group15Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group15FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group15Rect)
        group15TextContent.draw(in: CGRect(x: group15Rect.minX, y: group15Rect.minY + (group15Rect.height - group15TextHeight) / 2, width: group15Rect.width, height: group15TextHeight), withAttributes: group15FontAttributes)
        context.restoreGState()


        //// Group 16 Drawing
        let group16Rect = CGRect(x: 542, y: 20, width: 35, height: 20)
        let group16TextContent = "VIA"
        let group16Style = NSMutableParagraphStyle()
        group16Style.alignment = .center
        let group16FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group16Style,
        ] as [NSAttributedStringKey: Any]

        let group16TextHeight: CGFloat = group16TextContent.boundingRect(with: CGSize(width: group16Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group16FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group16Rect)
        group16TextContent.draw(in: CGRect(x: group16Rect.minX, y: group16Rect.minY + (group16Rect.height - group16TextHeight) / 2, width: group16Rect.width, height: group16TextHeight), withAttributes: group16FontAttributes)
        context.restoreGState()


        //// Group 17 Drawing
        let group17Rect = CGRect(x: 577, y: 20, width: 35, height: 20)
        let group17TextContent = "VIIA"
        let group17Style = NSMutableParagraphStyle()
        group17Style.alignment = .center
        let group17FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group17Style,
        ] as [NSAttributedStringKey: Any]

        let group17TextHeight: CGFloat = group17TextContent.boundingRect(with: CGSize(width: group17Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group17FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group17Rect)
        group17TextContent.draw(in: CGRect(x: group17Rect.minX, y: group17Rect.minY + (group17Rect.height - group17TextHeight) / 2, width: group17Rect.width, height: group17TextHeight), withAttributes: group17FontAttributes)
        context.restoreGState()


        //// Group 18 Drawing
        let group18Rect = CGRect(x: 612, y: 20, width: 35, height: 20)
        let group18TextContent = "VIIIA"
        let group18Style = NSMutableParagraphStyle()
        group18Style.alignment = .center
        let group18FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: group18Style,
        ] as [NSAttributedStringKey: Any]

        let group18TextHeight: CGFloat = group18TextContent.boundingRect(with: CGSize(width: group18Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: group18FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: group18Rect)
        group18TextContent.draw(in: CGRect(x: group18Rect.minX, y: group18Rect.minY + (group18Rect.height - group18TextHeight) / 2, width: group18Rect.width, height: group18TextHeight), withAttributes: group18FontAttributes)
        context.restoreGState()


        //// IUPAC Group 1 Drawing
        let iUPACGroup1Rect = CGRect(x: 17, y: 6, width: 35, height: 20)
        let iUPACGroup1TextContent = "1"
        let iUPACGroup1Style = NSMutableParagraphStyle()
        iUPACGroup1Style.alignment = .center
        let iUPACGroup1FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup1Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup1TextHeight: CGFloat = iUPACGroup1TextContent.boundingRect(with: CGSize(width: iUPACGroup1Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup1FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup1Rect)
        iUPACGroup1TextContent.draw(in: CGRect(x: iUPACGroup1Rect.minX, y: iUPACGroup1Rect.minY + (iUPACGroup1Rect.height - iUPACGroup1TextHeight) / 2, width: iUPACGroup1Rect.width, height: iUPACGroup1TextHeight), withAttributes: iUPACGroup1FontAttributes)
        context.restoreGState()


        //// IUPAC Group 2 Drawing
        let iUPACGroup2Rect = CGRect(x: 53, y: 6, width: 35, height: 20)
        let iUPACGroup2TextContent = "2"
        let iUPACGroup2Style = NSMutableParagraphStyle()
        iUPACGroup2Style.alignment = .center
        let iUPACGroup2FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup2Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup2TextHeight: CGFloat = iUPACGroup2TextContent.boundingRect(with: CGSize(width: iUPACGroup2Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup2FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup2Rect)
        iUPACGroup2TextContent.draw(in: CGRect(x: iUPACGroup2Rect.minX, y: iUPACGroup2Rect.minY + (iUPACGroup2Rect.height - iUPACGroup2TextHeight) / 2, width: iUPACGroup2Rect.width, height: iUPACGroup2TextHeight), withAttributes: iUPACGroup2FontAttributes)
        context.restoreGState()


        //// IUPAC Group 3 Drawing
        let iUPACGroup3Rect = CGRect(x: 88, y: 6, width: 35, height: 20)
        let iUPACGroup3TextContent = "3"
        let iUPACGroup3Style = NSMutableParagraphStyle()
        iUPACGroup3Style.alignment = .center
        let iUPACGroup3FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup3Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup3TextHeight: CGFloat = iUPACGroup3TextContent.boundingRect(with: CGSize(width: iUPACGroup3Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup3FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup3Rect)
        iUPACGroup3TextContent.draw(in: CGRect(x: iUPACGroup3Rect.minX, y: iUPACGroup3Rect.minY + (iUPACGroup3Rect.height - iUPACGroup3TextHeight) / 2, width: iUPACGroup3Rect.width, height: iUPACGroup3TextHeight), withAttributes: iUPACGroup3FontAttributes)
        context.restoreGState()


        //// IUPAC Group 4 Drawing
        let iUPACGroup4Rect = CGRect(x: 122, y: 6, width: 35, height: 20)
        let iUPACGroup4TextContent = "4"
        let iUPACGroup4Style = NSMutableParagraphStyle()
        iUPACGroup4Style.alignment = .center
        let iUPACGroup4FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup4Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup4TextHeight: CGFloat = iUPACGroup4TextContent.boundingRect(with: CGSize(width: iUPACGroup4Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup4FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup4Rect)
        iUPACGroup4TextContent.draw(in: CGRect(x: iUPACGroup4Rect.minX, y: iUPACGroup4Rect.minY + (iUPACGroup4Rect.height - iUPACGroup4TextHeight) / 2, width: iUPACGroup4Rect.width, height: iUPACGroup4TextHeight), withAttributes: iUPACGroup4FontAttributes)
        context.restoreGState()


        //// IUPAC Group 5 Drawing
        let iUPACGroup5Rect = CGRect(x: 157, y: 6, width: 35, height: 20)
        let iUPACGroup5TextContent = "5"
        let iUPACGroup5Style = NSMutableParagraphStyle()
        iUPACGroup5Style.alignment = .center
        let iUPACGroup5FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup5Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup5TextHeight: CGFloat = iUPACGroup5TextContent.boundingRect(with: CGSize(width: iUPACGroup5Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup5FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup5Rect)
        iUPACGroup5TextContent.draw(in: CGRect(x: iUPACGroup5Rect.minX, y: iUPACGroup5Rect.minY + (iUPACGroup5Rect.height - iUPACGroup5TextHeight) / 2, width: iUPACGroup5Rect.width, height: iUPACGroup5TextHeight), withAttributes: iUPACGroup5FontAttributes)
        context.restoreGState()


        //// IUPAC Group 6 Drawing
        let iUPACGroup6Rect = CGRect(x: 192, y: 6, width: 35, height: 20)
        let iUPACGroup6TextContent = "6"
        let iUPACGroup6Style = NSMutableParagraphStyle()
        iUPACGroup6Style.alignment = .center
        let iUPACGroup6FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup6Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup6TextHeight: CGFloat = iUPACGroup6TextContent.boundingRect(with: CGSize(width: iUPACGroup6Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup6FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup6Rect)
        iUPACGroup6TextContent.draw(in: CGRect(x: iUPACGroup6Rect.minX, y: iUPACGroup6Rect.minY + (iUPACGroup6Rect.height - iUPACGroup6TextHeight) / 2, width: iUPACGroup6Rect.width, height: iUPACGroup6TextHeight), withAttributes: iUPACGroup6FontAttributes)
        context.restoreGState()


        //// IUPAC Group 7 Drawing
        let iUPACGroup7Rect = CGRect(x: 227, y: 6, width: 35, height: 20)
        let iUPACGroup7TextContent = "7"
        let iUPACGroup7Style = NSMutableParagraphStyle()
        iUPACGroup7Style.alignment = .center
        let iUPACGroup7FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup7Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup7TextHeight: CGFloat = iUPACGroup7TextContent.boundingRect(with: CGSize(width: iUPACGroup7Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup7FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup7Rect)
        iUPACGroup7TextContent.draw(in: CGRect(x: iUPACGroup7Rect.minX, y: iUPACGroup7Rect.minY + (iUPACGroup7Rect.height - iUPACGroup7TextHeight) / 2, width: iUPACGroup7Rect.width, height: iUPACGroup7TextHeight), withAttributes: iUPACGroup7FontAttributes)
        context.restoreGState()


        //// IUPAC Group 11 Drawing
        let iUPACGroup11Rect = CGRect(x: 367, y: 6, width: 35, height: 20)
        let iUPACGroup11TextContent = "11"
        let iUPACGroup11Style = NSMutableParagraphStyle()
        iUPACGroup11Style.alignment = .center
        let iUPACGroup11FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup11Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup11TextHeight: CGFloat = iUPACGroup11TextContent.boundingRect(with: CGSize(width: iUPACGroup11Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup11FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup11Rect)
        iUPACGroup11TextContent.draw(in: CGRect(x: iUPACGroup11Rect.minX, y: iUPACGroup11Rect.minY + (iUPACGroup11Rect.height - iUPACGroup11TextHeight) / 2, width: iUPACGroup11Rect.width, height: iUPACGroup11TextHeight), withAttributes: iUPACGroup11FontAttributes)
        context.restoreGState()


        //// IUPAC Group 12 Drawing
        let iUPACGroup12Rect = CGRect(x: 402, y: 6, width: 35, height: 20)
        let iUPACGroup12TextContent = "12"
        let iUPACGroup12Style = NSMutableParagraphStyle()
        iUPACGroup12Style.alignment = .center
        let iUPACGroup12FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup12Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup12TextHeight: CGFloat = iUPACGroup12TextContent.boundingRect(with: CGSize(width: iUPACGroup12Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup12FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup12Rect)
        iUPACGroup12TextContent.draw(in: CGRect(x: iUPACGroup12Rect.minX, y: iUPACGroup12Rect.minY + (iUPACGroup12Rect.height - iUPACGroup12TextHeight) / 2, width: iUPACGroup12Rect.width, height: iUPACGroup12TextHeight), withAttributes: iUPACGroup12FontAttributes)
        context.restoreGState()


        //// IUPAC Group 13 Drawing
        let iUPACGroup13Rect = CGRect(x: 437, y: 6, width: 35, height: 20)
        let iUPACGroup13TextContent = "13"
        let iUPACGroup13Style = NSMutableParagraphStyle()
        iUPACGroup13Style.alignment = .center
        let iUPACGroup13FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup13Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup13TextHeight: CGFloat = iUPACGroup13TextContent.boundingRect(with: CGSize(width: iUPACGroup13Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup13FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup13Rect)
        iUPACGroup13TextContent.draw(in: CGRect(x: iUPACGroup13Rect.minX, y: iUPACGroup13Rect.minY + (iUPACGroup13Rect.height - iUPACGroup13TextHeight) / 2, width: iUPACGroup13Rect.width, height: iUPACGroup13TextHeight), withAttributes: iUPACGroup13FontAttributes)
        context.restoreGState()


        //// IUPAC Group 14 Drawing
        let iUPACGroup14Rect = CGRect(x: 472, y: 6, width: 35, height: 20)
        let iUPACGroup14TextContent = "14"
        let iUPACGroup14Style = NSMutableParagraphStyle()
        iUPACGroup14Style.alignment = .center
        let iUPACGroup14FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup14Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup14TextHeight: CGFloat = iUPACGroup14TextContent.boundingRect(with: CGSize(width: iUPACGroup14Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup14FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup14Rect)
        iUPACGroup14TextContent.draw(in: CGRect(x: iUPACGroup14Rect.minX, y: iUPACGroup14Rect.minY + (iUPACGroup14Rect.height - iUPACGroup14TextHeight) / 2, width: iUPACGroup14Rect.width, height: iUPACGroup14TextHeight), withAttributes: iUPACGroup14FontAttributes)
        context.restoreGState()


        //// IUPAC Group 15 Drawing
        let iUPACGroup15Rect = CGRect(x: 507, y: 6, width: 35, height: 20)
        let iUPACGroup15TextContent = "15"
        let iUPACGroup15Style = NSMutableParagraphStyle()
        iUPACGroup15Style.alignment = .center
        let iUPACGroup15FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup15Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup15TextHeight: CGFloat = iUPACGroup15TextContent.boundingRect(with: CGSize(width: iUPACGroup15Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup15FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup15Rect)
        iUPACGroup15TextContent.draw(in: CGRect(x: iUPACGroup15Rect.minX, y: iUPACGroup15Rect.minY + (iUPACGroup15Rect.height - iUPACGroup15TextHeight) / 2, width: iUPACGroup15Rect.width, height: iUPACGroup15TextHeight), withAttributes: iUPACGroup15FontAttributes)
        context.restoreGState()


        //// IUPAC Group 16 Drawing
        let iUPACGroup16Rect = CGRect(x: 542, y: 6, width: 35, height: 20)
        let iUPACGroup16TextContent = "16"
        let iUPACGroup16Style = NSMutableParagraphStyle()
        iUPACGroup16Style.alignment = .center
        let iUPACGroup16FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup16Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup16TextHeight: CGFloat = iUPACGroup16TextContent.boundingRect(with: CGSize(width: iUPACGroup16Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup16FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup16Rect)
        iUPACGroup16TextContent.draw(in: CGRect(x: iUPACGroup16Rect.minX, y: iUPACGroup16Rect.minY + (iUPACGroup16Rect.height - iUPACGroup16TextHeight) / 2, width: iUPACGroup16Rect.width, height: iUPACGroup16TextHeight), withAttributes: iUPACGroup16FontAttributes)
        context.restoreGState()


        //// IUPAC Group 17 Drawing
        let iUPACGroup17Rect = CGRect(x: 577, y: 6, width: 35, height: 20)
        let iUPACGroup17TextContent = "17"
        let iUPACGroup17Style = NSMutableParagraphStyle()
        iUPACGroup17Style.alignment = .center
        let iUPACGroup17FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup17Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup17TextHeight: CGFloat = iUPACGroup17TextContent.boundingRect(with: CGSize(width: iUPACGroup17Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup17FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup17Rect)
        iUPACGroup17TextContent.draw(in: CGRect(x: iUPACGroup17Rect.minX, y: iUPACGroup17Rect.minY + (iUPACGroup17Rect.height - iUPACGroup17TextHeight) / 2, width: iUPACGroup17Rect.width, height: iUPACGroup17TextHeight), withAttributes: iUPACGroup17FontAttributes)
        context.restoreGState()


        //// IUPAC Group 18 Drawing
        let iUPACGroup18Rect = CGRect(x: 612, y: 6, width: 35, height: 20)
        let iUPACGroup18TextContent = "18"
        let iUPACGroup18Style = NSMutableParagraphStyle()
        iUPACGroup18Style.alignment = .center
        let iUPACGroup18FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup18Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup18TextHeight: CGFloat = iUPACGroup18TextContent.boundingRect(with: CGSize(width: iUPACGroup18Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup18FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup18Rect)
        iUPACGroup18TextContent.draw(in: CGRect(x: iUPACGroup18Rect.minX, y: iUPACGroup18Rect.minY + (iUPACGroup18Rect.height - iUPACGroup18TextHeight) / 2, width: iUPACGroup18Rect.width, height: iUPACGroup18TextHeight), withAttributes: iUPACGroup18FontAttributes)
        context.restoreGState()


        //// IUPAC Group 8 Drawing
        let iUPACGroup8Rect = CGRect(x: 262, y: 6, width: 35, height: 20)
        let iUPACGroup8TextContent = "8"
        let iUPACGroup8Style = NSMutableParagraphStyle()
        iUPACGroup8Style.alignment = .center
        let iUPACGroup8FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup8Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup8TextHeight: CGFloat = iUPACGroup8TextContent.boundingRect(with: CGSize(width: iUPACGroup8Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup8FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup8Rect)
        iUPACGroup8TextContent.draw(in: CGRect(x: iUPACGroup8Rect.minX, y: iUPACGroup8Rect.minY + (iUPACGroup8Rect.height - iUPACGroup8TextHeight) / 2, width: iUPACGroup8Rect.width, height: iUPACGroup8TextHeight), withAttributes: iUPACGroup8FontAttributes)
        context.restoreGState()


        //// IUPAC Group 9 Drawing
        let iUPACGroup9Rect = CGRect(x: 297, y: 6, width: 35, height: 20)
        let iUPACGroup9TextContent = "9"
        let iUPACGroup9Style = NSMutableParagraphStyle()
        iUPACGroup9Style.alignment = .center
        let iUPACGroup9FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup9Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup9TextHeight: CGFloat = iUPACGroup9TextContent.boundingRect(with: CGSize(width: iUPACGroup9Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup9FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup9Rect)
        iUPACGroup9TextContent.draw(in: CGRect(x: iUPACGroup9Rect.minX, y: iUPACGroup9Rect.minY + (iUPACGroup9Rect.height - iUPACGroup9TextHeight) / 2, width: iUPACGroup9Rect.width, height: iUPACGroup9TextHeight), withAttributes: iUPACGroup9FontAttributes)
        context.restoreGState()


        //// IUPAC Group 10 Drawing
        let iUPACGroup10Rect = CGRect(x: 332, y: 6, width: 35, height: 20)
        let iUPACGroup10TextContent = "10"
        let iUPACGroup10Style = NSMutableParagraphStyle()
        iUPACGroup10Style.alignment = .center
        let iUPACGroup10FontAttributes = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black,
            .paragraphStyle: iUPACGroup10Style,
        ] as [NSAttributedStringKey: Any]

        let iUPACGroup10TextHeight: CGFloat = iUPACGroup10TextContent.boundingRect(with: CGSize(width: iUPACGroup10Rect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: iUPACGroup10FontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: iUPACGroup10Rect)
        iUPACGroup10TextContent.draw(in: CGRect(x: iUPACGroup10Rect.minX, y: iUPACGroup10Rect.minY + (iUPACGroup10Rect.height - iUPACGroup10TextHeight) / 2, width: iUPACGroup10Rect.width, height: iUPACGroup10TextHeight), withAttributes: iUPACGroup10FontAttributes)
        context.restoreGState()


        //// legend alkali Drawing
        let legendAlkaliPath = UIBezierPath(rect: CGRect(x: 103, y: 47, width: 20, height: 20))
        PeriodicTableBackground.alkaliMetalsColor.setFill()
        legendAlkaliPath.fill()


        //// Alkali metals legend text Drawing
        let alkaliMetalsLegendTextRect = CGRect(x: 124, y: 47, width: 78, height: 20)
        let alkaliMetalsLegendTextTextContent = "Alkali metals"
        let alkaliMetalsLegendTextStyle = NSMutableParagraphStyle()
        alkaliMetalsLegendTextStyle.alignment = .left
        let alkaliMetalsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: alkaliMetalsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let alkaliMetalsLegendTextTextHeight: CGFloat = alkaliMetalsLegendTextTextContent.boundingRect(with: CGSize(width: alkaliMetalsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: alkaliMetalsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: alkaliMetalsLegendTextRect)
        alkaliMetalsLegendTextTextContent.draw(in: CGRect(x: alkaliMetalsLegendTextRect.minX, y: alkaliMetalsLegendTextRect.minY + (alkaliMetalsLegendTextRect.height - alkaliMetalsLegendTextTextHeight) / 2, width: alkaliMetalsLegendTextRect.width, height: alkaliMetalsLegendTextTextHeight), withAttributes: alkaliMetalsLegendTextFontAttributes)
        context.restoreGState()


        //// legend alkaline Drawing
        let legendAlkalinePath = UIBezierPath(rect: CGRect(x: 103, y: 67, width: 20, height: 20))
        PeriodicTableBackground.alkalineEarthMetalsColor.setFill()
        legendAlkalinePath.fill()


        //// Alkaline earth metals legend text Drawing
        let alkalineEarthMetalsLegendTextRect = CGRect(x: 124, y: 67, width: 115, height: 20)
        let alkalineEarthMetalsLegendTextTextContent = "Alkaline earth metals"
        let alkalineEarthMetalsLegendTextStyle = NSMutableParagraphStyle()
        alkalineEarthMetalsLegendTextStyle.alignment = .left
        let alkalineEarthMetalsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: alkalineEarthMetalsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let alkalineEarthMetalsLegendTextTextHeight: CGFloat = alkalineEarthMetalsLegendTextTextContent.boundingRect(with: CGSize(width: alkalineEarthMetalsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: alkalineEarthMetalsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: alkalineEarthMetalsLegendTextRect)
        alkalineEarthMetalsLegendTextTextContent.draw(in: CGRect(x: alkalineEarthMetalsLegendTextRect.minX, y: alkalineEarthMetalsLegendTextRect.minY + (alkalineEarthMetalsLegendTextRect.height - alkalineEarthMetalsLegendTextTextHeight) / 2, width: alkalineEarthMetalsLegendTextRect.width, height: alkalineEarthMetalsLegendTextTextHeight), withAttributes: alkalineEarthMetalsLegendTextFontAttributes)
        context.restoreGState()


        //// legend lanthanoid Drawing
        let legendLanthanoidPath = UIBezierPath(rect: CGRect(x: 103, y: 87, width: 20, height: 20))
        PeriodicTableBackground.lanthanoidsColor.setFill()
        legendLanthanoidPath.fill()


        //// Lanthanoids legend text Drawing
        let lanthanoidsLegendTextRect = CGRect(x: 124, y: 87, width: 78, height: 20)
        let lanthanoidsLegendTextTextContent = "Lanthanoids"
        let lanthanoidsLegendTextStyle = NSMutableParagraphStyle()
        lanthanoidsLegendTextStyle.alignment = .left
        let lanthanoidsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: lanthanoidsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let lanthanoidsLegendTextTextHeight: CGFloat = lanthanoidsLegendTextTextContent.boundingRect(with: CGSize(width: lanthanoidsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: lanthanoidsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: lanthanoidsLegendTextRect)
        lanthanoidsLegendTextTextContent.draw(in: CGRect(x: lanthanoidsLegendTextRect.minX, y: lanthanoidsLegendTextRect.minY + (lanthanoidsLegendTextRect.height - lanthanoidsLegendTextTextHeight) / 2, width: lanthanoidsLegendTextRect.width, height: lanthanoidsLegendTextTextHeight), withAttributes: lanthanoidsLegendTextFontAttributes)
        context.restoreGState()


        //// legend actinoid Drawing
        let legendActinoidPath = UIBezierPath(rect: CGRect(x: 103, y: 107, width: 20, height: 20))
        PeriodicTableBackground.actinoidsColor.setFill()
        legendActinoidPath.fill()


        //// Actinoids legend text Drawing
        let actinoidsLegendTextRect = CGRect(x: 124, y: 107, width: 78, height: 20)
        let actinoidsLegendTextTextContent = "Actinoids"
        let actinoidsLegendTextStyle = NSMutableParagraphStyle()
        actinoidsLegendTextStyle.alignment = .left
        let actinoidsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: actinoidsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let actinoidsLegendTextTextHeight: CGFloat = actinoidsLegendTextTextContent.boundingRect(with: CGSize(width: actinoidsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: actinoidsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: actinoidsLegendTextRect)
        actinoidsLegendTextTextContent.draw(in: CGRect(x: actinoidsLegendTextRect.minX, y: actinoidsLegendTextRect.minY + (actinoidsLegendTextRect.height - actinoidsLegendTextTextHeight) / 2, width: actinoidsLegendTextRect.width, height: actinoidsLegendTextTextHeight), withAttributes: actinoidsLegendTextFontAttributes)
        context.restoreGState()


        //// legend transition metals Drawing
        let legendTransitionMetalsPath = UIBezierPath(rect: CGRect(x: 239, y: 47, width: 20, height: 20))
        PeriodicTableBackground.transitionMetalsColor.setFill()
        legendTransitionMetalsPath.fill()


        //// Transition metals legen text Drawing
        let transitionMetalsLegenTextRect = CGRect(x: 260, y: 47, width: 107, height: 20)
        let transitionMetalsLegenTextTextContent = "Transition metals"
        let transitionMetalsLegenTextStyle = NSMutableParagraphStyle()
        transitionMetalsLegenTextStyle.alignment = .left
        let transitionMetalsLegenTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: transitionMetalsLegenTextStyle,
        ] as [NSAttributedStringKey: Any]

        let transitionMetalsLegenTextTextHeight: CGFloat = transitionMetalsLegenTextTextContent.boundingRect(with: CGSize(width: transitionMetalsLegenTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: transitionMetalsLegenTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: transitionMetalsLegenTextRect)
        transitionMetalsLegenTextTextContent.draw(in: CGRect(x: transitionMetalsLegenTextRect.minX, y: transitionMetalsLegenTextRect.minY + (transitionMetalsLegenTextRect.height - transitionMetalsLegenTextTextHeight) / 2, width: transitionMetalsLegenTextRect.width, height: transitionMetalsLegenTextTextHeight), withAttributes: transitionMetalsLegenTextFontAttributes)
        context.restoreGState()


        //// legend Post-transition metals Drawing
        let legendPosttransitionMetalsPath = UIBezierPath(rect: CGRect(x: 239, y: 67, width: 20, height: 20))
        PeriodicTableBackground.postTransitionMetalColor.setFill()
        legendPosttransitionMetalsPath.fill()


        //// Post-transition metals legend text Drawing
        let posttransitionMetalsLegendTextRect = CGRect(x: 260, y: 67, width: 125, height: 20)
        let posttransitionMetalsLegendTextTextContent = "Post-transition metals"
        let posttransitionMetalsLegendTextStyle = NSMutableParagraphStyle()
        posttransitionMetalsLegendTextStyle.alignment = .left
        let posttransitionMetalsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: posttransitionMetalsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let posttransitionMetalsLegendTextTextHeight: CGFloat = posttransitionMetalsLegendTextTextContent.boundingRect(with: CGSize(width: posttransitionMetalsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: posttransitionMetalsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: posttransitionMetalsLegendTextRect)
        posttransitionMetalsLegendTextTextContent.draw(in: CGRect(x: posttransitionMetalsLegendTextRect.minX, y: posttransitionMetalsLegendTextRect.minY + (posttransitionMetalsLegendTextRect.height - posttransitionMetalsLegendTextTextHeight) / 2, width: posttransitionMetalsLegendTextRect.width, height: posttransitionMetalsLegendTextTextHeight), withAttributes: posttransitionMetalsLegendTextFontAttributes)
        context.restoreGState()


        //// legend other nonmetals Drawing
        let legendOtherNonmetalsPath = UIBezierPath(rect: CGRect(x: 239, y: 87, width: 20, height: 20))
        PeriodicTableBackground.otherNonMetalsColor.setFill()
        legendOtherNonmetalsPath.fill()


        //// other nonmetals legend text Drawing
        let otherNonmetalsLegendTextRect = CGRect(x: 260, y: 87, width: 125, height: 20)
        let otherNonmetalsLegendTextTextContent = "Other nonmetals"
        let otherNonmetalsLegendTextStyle = NSMutableParagraphStyle()
        otherNonmetalsLegendTextStyle.alignment = .left
        let otherNonmetalsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: otherNonmetalsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let otherNonmetalsLegendTextTextHeight: CGFloat = otherNonmetalsLegendTextTextContent.boundingRect(with: CGSize(width: otherNonmetalsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: otherNonmetalsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: otherNonmetalsLegendTextRect)
        otherNonmetalsLegendTextTextContent.draw(in: CGRect(x: otherNonmetalsLegendTextRect.minX, y: otherNonmetalsLegendTextRect.minY + (otherNonmetalsLegendTextRect.height - otherNonmetalsLegendTextTextHeight) / 2, width: otherNonmetalsLegendTextRect.width, height: otherNonmetalsLegendTextTextHeight), withAttributes: otherNonmetalsLegendTextFontAttributes)
        context.restoreGState()


        //// legend noble glases Drawing
        let legendNobleGlasesPath = UIBezierPath(rect: CGRect(x: 239, y: 107, width: 20, height: 20))
        PeriodicTableBackground.nobleGasesColor.setFill()
        legendNobleGlasesPath.fill()


        //// noble gases legend text Drawing
        let nobleGasesLegendTextRect = CGRect(x: 260, y: 107, width: 125, height: 20)
        let nobleGasesLegendTextTextContent = "Noble gases"
        let nobleGasesLegendTextStyle = NSMutableParagraphStyle()
        nobleGasesLegendTextStyle.alignment = .left
        let nobleGasesLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: nobleGasesLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let nobleGasesLegendTextTextHeight: CGFloat = nobleGasesLegendTextTextContent.boundingRect(with: CGSize(width: nobleGasesLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: nobleGasesLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: nobleGasesLegendTextRect)
        nobleGasesLegendTextTextContent.draw(in: CGRect(x: nobleGasesLegendTextRect.minX, y: nobleGasesLegendTextRect.minY + (nobleGasesLegendTextRect.height - nobleGasesLegendTextTextHeight) / 2, width: nobleGasesLegendTextRect.width, height: nobleGasesLegendTextTextHeight), withAttributes: nobleGasesLegendTextFontAttributes)
        context.restoreGState()


        //// legend metalloids Drawing
        let legendMetalloidsPath = UIBezierPath(rect: CGRect(x: 385, y: 47, width: 20, height: 20))
        PeriodicTableBackground.metalloidsColor.setFill()
        legendMetalloidsPath.fill()


        //// metalloinds legend text Drawing
        let metalloindsLegendTextRect = CGRect(x: 406, y: 47, width: 66, height: 20)
        let metalloindsLegendTextTextContent = "Metalloids"
        let metalloindsLegendTextStyle = NSMutableParagraphStyle()
        metalloindsLegendTextStyle.alignment = .left
        let metalloindsLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: metalloindsLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let metalloindsLegendTextTextHeight: CGFloat = metalloindsLegendTextTextContent.boundingRect(with: CGSize(width: metalloindsLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: metalloindsLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: metalloindsLegendTextRect)
        metalloindsLegendTextTextContent.draw(in: CGRect(x: metalloindsLegendTextRect.minX, y: metalloindsLegendTextRect.minY + (metalloindsLegendTextRect.height - metalloindsLegendTextTextHeight) / 2, width: metalloindsLegendTextRect.width, height: metalloindsLegendTextTextHeight), withAttributes: metalloindsLegendTextFontAttributes)
        context.restoreGState()


        //// legend unknown Drawing
        let legendUnknownPath = UIBezierPath(rect: CGRect(x: 490, y: 47, width: 20, height: 20))
        PeriodicTableBackground.unknownColor.setFill()
        legendUnknownPath.fill()


        //// unknown legend text Drawing
        let unknownLegendTextRect = CGRect(x: 511, y: 47, width: 66, height: 20)
        let unknownLegendTextTextContent = "Unknown"
        let unknownLegendTextStyle = NSMutableParagraphStyle()
        unknownLegendTextStyle.alignment = .left
        let unknownLegendTextFontAttributes = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.black,
            .paragraphStyle: unknownLegendTextStyle,
        ] as [NSAttributedStringKey: Any]

        let unknownLegendTextTextHeight: CGFloat = unknownLegendTextTextContent.boundingRect(with: CGSize(width: unknownLegendTextRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: unknownLegendTextFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: unknownLegendTextRect)
        unknownLegendTextTextContent.draw(in: CGRect(x: unknownLegendTextRect.minX, y: unknownLegendTextRect.minY + (unknownLegendTextRect.height - unknownLegendTextTextHeight) / 2, width: unknownLegendTextRect.width, height: unknownLegendTextTextHeight), withAttributes: unknownLegendTextFontAttributes)
        context.restoreGState()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        PeriodicTableBackground.hydrogenColor.setFill()
        bezierPath.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 262, y: 29, width: 41, height: 1))
        UIColor.black.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 326, y: 29, width: 41, height: 1))
        UIColor.black.setFill()
        rectangle2Path.fill()
        
        context.restoreGState()

    }




    @objc(PeriodicTableBackgroundResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
